title: Caribbean Country Trainings
description: A website template for the SIG Caribbean trainings
baseurl: "/caribbean-trainings" # the subpath of your site, e.g. /blog
url: "https://hayleypippin.github.io" # the base hostname & protocol for your site, e.g. http://example.com

remote_theme: just-the-docs/just-the-docs
